routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect('/tasks');
});

Auth::routes();


Route::get('/users', function(){
    return \App\User::all();
});



Route::middleware(['auth'])->group(function () {
    Route::get('/authored', 'TasksController@authored')->name('tasks.authored');

    Route::resource('tasks', 'TasksController');
    Route::put('/userUpdate/{id}', 'TasksController@statusUpdate')->name('tasks.userUpdate');
});

app/Task.php
<?php

namespace App;

use App\User;
use App\Http\Traits\TimestampTrait;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = ['author_id'];
    
    public function author()
    {
        return $this->belongsTo(\App\User::class, 'author_id');
    }

    public function user()
    {
        return $this->belongsTo(\App\User::class, 'user_id');
    }

    public static function rules($id = '')
    {
        return [
            'name' => 'required|string|max:255',
            'description' => 'required|string|max:10000',
            'due_date' => 'required|date_format:Y-m-d\TH:i|after:'.(date('Y-m-d H:i')),
            'status' => 'integer|between:1,2',
            'user_id' => 'exists:App\User,id',
            

        ];
    }



    public function format(){

        return [
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'due_date' => dateFormat($this->due_date),
            'status' => $this->status,
            'created_at' => dateFormat($this->created_at),
            'user_id' => $this->user_id,
            'user_name' => $this->user->name,
            'user_email' => $this->user->email,
            'author_id' => $this->author_id,
            'author_name' => $this->author->name,
            'author_email' => $this->author->email,
        ];
    }
}

app/Http/Controllers/Api/TasksController.php
<?php

namespace App\Http\Controllers\Api;

use Auth;
use App\Task;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Api\TaskRepositoryInterface;


class TasksController extends Controller
{
    private $taskRepository;
    
    public function __construct(TaskRepositoryInterface $taskRepository)
    {
        $this->taskRepository  = $taskRepository;
    }





    //get all tasks which are assigned to logged in user
    public function index()
    {
        return $this->taskRepository->getAllTasks();
    }


    
    //show single task (if logged in user is  author or assigned user )
    public function show($id)
    {
        return $this->taskRepository->getById($id);
    }

    //if logged in create new task
    public function store(Request $request)
    {
        return $this->taskRepository->create($request);
    }

    //if logged in user is author of the specific task: update
    public function update(Request $request, $id)
    {
        return $this->taskRepository->update($request, $id);
    }

    //if logged in user is author of the specific task:  delete 
    public function destroy($id)
    {
        return $this->taskRepository->delete($id);
    }

    //get all tasks which created logged in user
    public function authoredTasks()
    {
        return $this->taskRepository->getAuthoredTasks();
    }


    //change task status (in progress 1, done - 2), if logged in user is author or assigned
    public function changeTaskStatus($id)
    {
        return $this->taskRepository->changeTaskStatus($id);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Task;
use App\User;
use Illuminate\Http\Request;
use App\Repositories\TaskRepository;
use App\Repositories\TaskRepositoryInterface;

class TasksController extends Controller
{

    private $taskRepository;
    public function __construct(TaskRepositoryInterface $taskRepository){
        $this->taskRepository = $taskRepository;
    }

    //get tasks which are assigned to signed in user
    public function index()
    {
        return $this->taskRepository->getAllTasks();
    }


    //get tasks which created signed in user
    public function authored()
    {
        return $this->taskRepository->getAuthoredTasks();
    }

    //return crete view with users list
    public function create()
    {

        return $this->taskRepository->create();
    }


    //save new task
    public function store(Request $request)
    {

        return $this->taskRepository->store($request);
  
    }


    //return edit view with current task and users list (check if logged in user owns current task)
    public function edit($id)
    {
        return $this->taskRepository->edit($id);
    }

    
    //update current task (check if logged in user owns current task)
    public function update(Request $request, $id)
    {
        return $this->taskRepository->update($request, $id);
    }

    //delete current task (check if logged in user owns current task)
    public function destroy($id)
    {
        return $this->taskRepository->delete($id);
    }

    //change task status (check if logged in user owns current task or is assigned to that task)
    public function statusUpdate($id)
    {
       
        return $this->taskRepository->statusUpdate($id);

    }
}

resources/views/tasks/authored.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>ToDo List</h1>

            @if(session('success'))
        <div class="alert alert-success">{{session('success')}}</div>
            @elseif(session('error'))
        <div class="alert alert-danger">{{session('error')}}</div>

            @endif
        </div>
    </div>

    <br>
    <hr>
    @if(count($todos) > 0)

    @foreach ($todos as $todo)

    @php
        if($todo->status == 0){
            $class = 'alert-warning';
            $text = 'Pending';

        }else if($todo->status == 1){
            $class = 'alert-info';
            $text = 'In progress';
        }else if($todo->status == 2){
            $class = 'alert-success';
            $text = 'Done';
        };
    @endphp
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">
                <div class="left-side" style="width: 74%; display:inline-block">
                    Task Name:   {{$todo->name}}
                    <div style="">Assigned To: {{Auth::user()->id == $todo->user->id ?' Me' : $todo->user->name}}</div>
                </div>
             <div style="width:25%; display:inline-block; margin:0; padding:5px 10px" class="alert  {{$class}}">Status: {{$text}}</div>
            </div>

                <div class="card-body">
                    <div class="left-side" style="width: 74%; display:inline-block">
                     {{$todo->description}}
                    </div>  

                <div style="float:right">
            
                </div>
                </div>

                <div class="card-footer">
                <div class="left-side" style="width: 50%; display:inline-block">
                    <p>Assigned: {{$todo->created_at->diffForHumans(null, false, true)}}</p>
                    <p>Time left:{{ \Carbon\Carbon::parse($todo->due_date)->diffForHumans(['parts' => 3]) }}</p>
                    {{-- <p>Standart Format:{{ date('Y-m-d g:ia', strtotime($todo->due_date)) }}</p> --}}

                      

                </div>

                <div class="left-side col-6" >
                Change task Status:
                <form method="POST" action="{{ route('tasks.userUpdate', $todo->id )}}">
                    @method('put')
                    @csrf

                    <select name="status" id="" class="form-control col-4" style="display: inline-block">
                        <option value="0" {{$todo->status == 0 ? 'selected' : ''}} disabled>pending</option>
                        <option value="1" {{$todo->status == 1 ? 'selected' : ''}}>In proggress</option>
                        <option value="2" {{$todo->status == 2 ? 'selected' : ''}}>Done</option>
                    </select>

                    
                    <div class="col-md-6" style="display: inline-block">
                        <button type="submit" class="btn btn-primary">
                            Change
                        </button>
                    </div>

                </form>
                </div>
                <hr>
                @if($todo->author_id == Auth::user()->id)

                <div class="left-side" style="float:right">
                <form action="{{route('tasks.destroy', $todo->id)}}" method="post">
                @method('delete')
                @csrf
                <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')" value="Delete">
                </form>
                </div>


                    <div style="float:left">
                        <a href="{{route('tasks.edit', $todo->id)}}" class="btn btn-info">Edit Todo</a>
                        </div>
                @endif



       
                   </div>
            </div>
        </div>
    </div>

    <br>
    <br>
    @endforeach
    {{ $todos->links() }}
    @else

    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>No Todos</h1>
        </div>
    </div>

    @endif
</div>
@endsection

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(session('success'))
            <div class="alert alert-success">{{session('success')}}</div>
                @elseif(session('error'))
                <div class="alert alert-success">{{session('error')}}</div>
                @endif
            <div class="card">
                <div class="card-header">Add Task</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.store') }}">
                        @csrf
        
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
        
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
        
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                      
                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
        
                            <div class="col-md-6">
                                {{-- <input id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description" autofocus> --}}

                                <textarea name="description" id="description" cols="30" rows="10" class="form-control  @error('description') is-invalid @enderror" required ></textarea>
        
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <label for="user_id" class="col-md-4 col-form-label text-md-right">Users</label>
        
                            <div class="col-md-6">
                                <select name="user_id" id="" class="form-control @error('user_id') is-invalid @enderror ">
                                    @foreach ($users as $user)
                                    <option value="{{$user->id}}" {{Auth::user()->id == $user->id ?'selected' : ''}} >
                                        {{$user->name}}
                                        {{Auth::user()->id == $user->id ?'(Me)' : ''}} 
                                    </option>
                                        
                                    @endforeach
                                </select>
        
                                @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Due Date</label>
        
                            <div class="col-md-6">
                            <input id="due_date" type="datetime-local" min="{{date('Y-m-d\TH:i')}}" class="form-control @error('due_date') is-invalid @enderror" name="due_date" value="{{ old('due_date') }}" required autocomplete="name" autofocus>
        
                                @error('due_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                    
        
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Add Todo
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(session('success'))
            <div class="alert alert-success">{{session('success')}}</div>
                @elseif(session('error'))
                <div class="alert alert-success">{{session('error')}}</div>
                @endif
            <div class="card">
                <div class="card-header">Add Task</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.update', $task->id) }}">
                        @csrf
                        @method('put')
        
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
        
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $task->name}}" required autocomplete="name" autofocus>
        
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
        
                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
        
                            <div class="col-md-6">
                                {{-- <input id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ $task->description }}" required autocomplete="description" autofocus> --}}

                                <textarea name="description" id="description" cols="30" rows="10" class="form-control  @error('description') is-invalid @enderror" required >{{ $task->description }}</textarea>
        
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Users</label>
        
                            <div class="col-md-6">
                                <select name="user_id" id="" class="form-control @error('user_id') is-invalid @enderror">
                                    @foreach ($users as $user)
                                    <option value="{{$user->id}}" {{$task->user_id == $user->id ?'selected' : ''}} >
                                        {{$user->name}}
                                        {{Auth::user()->id == $user->id ?'(Me)' : ''}} 
                                    </option>
                                        
                                    @endforeach
                                </select>
        
                                @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Due Date</label>
        
                            <div class="col-md-6">
                            <input id="due_date" type="datetime-local" min="{{date('Y-m-d\TH:i')}}" class="form-control @error('due_date') is-invalid @enderror" name="due_date" value="{{ date('Y-m-d\TH:i', strtotime($task->due_date))}}" required autocomplete="due_date" autofocus >
        
                                @error('due_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                    
        
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Update Todo
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>ToDo List</h1>

            @if(session('success'))
        <div class="alert alert-success">{{session('success')}}</div>
            @elseif(session('error'))
        <div class="alert alert-danger">{{session('error')}}</div>

            @endif
        </div>
    </div>

    <br>
    <hr>
    @if(count($todos) > 0)

    @foreach ($todos as $todo)

    @php
        if($todo->status == 0){
            $class = 'alert-warning';
            $text = 'Pending';

        }else if($todo->status == 1){
            $class = 'alert-info';
            $text = 'In progress';
        }else if($todo->status == 2){
            $class = 'alert-success';
            $text = 'Done';
        };
    @endphp
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">
                <div class="left-side" style="width: 74%; display:inline-block">
                    Task Name:   {{$todo->name}}
                    <div style="">Assigned By: {{Auth::user()->id == $todo->author->id ?' Me' : $todo->author->name}}</div>
                </div>
             <div style="width:25%; display:inline-block; margin:0; padding:5px 10px" class="alert  {{$class}}">Status: {{$text}}</div>
            </div>

                <div class="card-body">
                    <div class="left-side" style="width: 74%; display:inline-block">
                     {{$todo->description}}
                    </div>  

                <div style="float:right">
            
                </div>
                </div>

                <div class="card-footer">
                <div class="left-side" style="width: 50%; display:inline-block">
                    <p>Assigned: {{$todo->created_at->diffForHumans(null, false, true)}}</p>
                    <p>Time left:{{ \Carbon\Carbon::parse($todo->due_date)->diffForHumans(['parts' => 3]) }}</p>
                    {{-- <p>Standart Format:{{ date('Y-m-d g:ia', strtotime($todo->due_date)) }}</p> --}}

                      

                </div>

                <div class="left-side col-6" >
                Change task Status:
                <form method="POST" action="{{ route('tasks.userUpdate', $todo->id )}}">
                    @method('put')
                    @csrf

                    <select name="status" id="" class="form-control col-4" style="display: inline-block">
                        <option value="0" {{$todo->status == 0 ? 'selected' : ''}} disabled>pending</option>
                        <option value="1" {{$todo->status == 1 ? 'selected' : ''}}>In proggress</option>
                        <option value="2" {{$todo->status == 2 ? 'selected' : ''}}>Done</option>
                    </select>

                    
                    <div class="col-md-6" style="display: inline-block">
                        <button type="submit" class="btn btn-primary">
                            Change
                        </button>
                    </div>

                </form>
                </div>
                <hr>
                @if($todo->author_id == Auth::user()->id)

                <div class="left-side" style="float:right">
                <form action="{{route('tasks.destroy', $todo->id)}}" method="post">
                @method('delete')
                @csrf
                <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')" value="Delete">
                </form>
                </div>


                    <div style="float:left">
                        <a href="{{route('tasks.edit', $todo->id)}}" class="btn btn-info">Edit Todo</a>
                        </div>
                @endif



       
                   </div>
            </div>
        </div>
    </div>

    <br>
    <br>
    @endforeach
    {{ $todos->links() }}
    @else

    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>No Todos</h1>
        </div>
    </div>

    @endif
</div>
@endsection